# --- First database schema

# --- !Ups

set ignorecase true;

create table user (
  id                        bigint generated by default as identity(start with 1000) not null,
  email                     varchar(255) not null,
  name                      varchar(255) not null,
  password                  varchar(255) not null,
  is_transporter            boolean,
  is_shipper                boolean,
  description               text,
  address                   text,
  constraint pk_employee primary key (id))
;

create table shipment (
  id                        bigint generated by default as identity(start with 1000) not null,
  reference                 varchar(255) not null,
  from_address              text,
  to_address                text,
  volume                    float,
  weight                    float,
  pieces                    int,
  booked                    boolean,
  expiration_date           date,
  pickup_time               timestamp,
  owner_id                  bigint,
  transporter_id            bigint,
  constraint pk_vacation primary key (id))
;

create sequence user_seq start with 1000;

create sequence shipment_seq start with 1000;


alter table shipment add constraint fk_shipment_user_1 foreign key (owner_id) references user (id) on delete restrict on update restrict;
alter table shipment add constraint fk_shipment_user_2 foreign key (transporter_id) references user (id) on delete restrict on update restrict;


create index idx_shipment_user_1 on shipment (owner_id);
create index idx_shipment_user_2 on shipment (transporter_id);


# --- !Downs

SET REFERENTIAL_INTEGRITY FALSE;

drop table if exists users;

drop table if exists shipment;


SET REFERENTIAL_INTEGRITY TRUE;

drop sequence if exists user_seq;

drop sequence if exists shipment_seq;
